### ISSUE TITLE
Chapter2/UnicodeDecodeError:'utf-8' 

### ISSUE THREAD

**Issue by cirby1** [rlvaugh/Real_World_Python#6]
**File "main.py", line 11, in main
    strings_by_author['doyle'] = text_to_string('hound.txt')
  File "main.py", line 31, in text_to_string
    return infile.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError:'utf-8' codec can't decode byte 0x93 in position 359**

Having issues running the Chapter 2 code on Debian 11 and I even tried porting it to the online IDE Replit. Is it just the quotation marks that are being misread? I'm not sure...

Here is a link to the Repl I made with the Chapter 2 code: https://replit.com/@CalvinIrby/IvoryBonyCoins#hound.txt

**Comment by rlvaugh** [comment]
Hi. Sorry you're having trouble. I think I see your problem. Please check out page 35 in the book, that discusses the encoding error some users may experience. Two lines of code are suggested that may fix the problem:

with open(filename, encoding='utf-8') as infile:

If that doesn't help, try:

with open(filename, encoding='utf-8', errors='ignore') as infile:

Where filename is the name of your text tile.

**Comment by cirby1** [comment]
Thank you for that! I believe that did the trick.
